server.port: 8080

spring:
  profiles:
    active: product
  application:
    name: admin
  config:
    import:
      - 'application-core.yml'
      - 'application-auth.yml'
      - 'application-domain.yml'
  thymeleaf:
    cache: false
